### ISSUE TITLE
Zelda Picross

### ISSUE THREAD

**Issue by BryMD** [salvacam/openjazz#2]
Hi again @salvacam :)

Regarding one of your other forks, Zelda Picross:
For some reason the 'surprise.ogg' sound effect is ear-shatteringly loud. Uploading the original un-amplified sound effect (transcoded to .ogg) here in case you'd be interested.

Enjoy ;)

Sincerely,
BryMD

[zeldapicross.zip](https://github.com/salvacam/openjazz/files/6196957/zeldapicross.zip)

**Comment by salvacam** [comment]
I have uploaded a revision of the release.
Thanks
